---
title: "Block report"
format:
  html:
    theme: cosmo
  pdf:
    documentclass: article
params:
  block_id: "40080D1SE"    # will be overridden from Shiny
  season: "All seasons"
execute:
  echo: false
  warning: false
  message: false
---

```{r}
# Load packages (tidyverse for data work)
library(tidyverse)
library(arrow)
library(gt)
library(sf)
library(basemaps)

source("R/plot_checklist_coords.R")

data_path <- "input/block_summary_seasons.parquet"

# Read in full project data, then filter down to a single block
block_id_param <- params$block_id
season_param <- params$season

bird_df <- open_dataset(data_path) |>
  filter(pba3_block == !!block_id_param, season == !!season_param) |>
  collect() |>
  st_drop_geometry()

ebd_df <- open_dataset("input/pa_breeding_bird_atlas_processed.parquet") |>
  filter(pba3_block == !!block_id_param) |>
  collect()

report_block_name <- ebd_df$block_name
```

## `{r} report_block_name` (`{r} block_id_param`)

### Species code summary

```{r}
bird_df |>
  dplyr::select(Confirmed, Probable, Possible, Observed) |>
  pivot_longer(everything(), names_to = "Code", values_to = "Count") |>
  gt()
```

### Effort summary

```{r}
bird_df |>
  dplyr::select(
    duration_hours_total,
    duration_hours_diurnal,
    duration_hours_nocturnal,
    duration_hours_unknown
  ) |>
  rename(
    Total = duration_hours_total,
    Diurnal = duration_hours_diurnal,
    Nocturnal = duration_hours_nocturnal,
    Unknown = duration_hours_unknown
  ) |>
  pivot_longer(everything(), names_to = "Effort type", values_to = "Value") |>
  mutate(Value = round(Value, 2)) |>
  gt()
```

```{r}
#glimpse(ebd_df)
```

```{r}
set_defaults(map_service = "esri", map_type = "natgeo_world_map")

plot_checklist_coords(ebd_df)
```